# Generated by Django 3.0.8 on 2020-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='lastUpadte',
            new_name='lastUpdate',
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
