# Generated by Django 3.0.8 on 2020-07-15 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0005_auto_20200715_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b724a7a4-b57d-4f24-9c3b-9198b95e9fed'), editable=False, primary_key=True, serialize=False),
        ),
    ]
