# Generated by Django 3.0.8 on 2020-07-15 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0006_auto_20200715_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
    ]
