# Generated by Django 3.0.8 on 2020-07-15 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0007_auto_20200715_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b8bfe8a-c6df-11ea-a500-00001dcd6500'), editable=False, primary_key=True, serialize=False),
        ),
    ]
