# Generated by Django 3.0.8 on 2020-07-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0008_auto_20200715_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default='b5237072c6df11eaa50000001dcd6500', editable=False, primary_key=True, serialize=False),
        ),
    ]
